### ISSUE TITLE
[v3] Module not found: Can't resolve 'timezones-list'

### ISSUE THREAD

**Issue by ApacheEx** [omsrivastava/timezones-list#4]
It looks like you have released a new version without "building" dist folder.

**Comment by omsrivastava** [comment]
The build has been published as version 3.0.1
Here is the commit - [c1fa0eb](https://github.com/omsrivastava/timezones-list/commit/c1fa0ebe1ed77def1d29cb923ed7c51c9d213c94)

**Comment by ApacheEx** [comment]
thanks, it works now
