### ISSUE TITLE
Invalid timezone

### ISSUE THREAD

**Issue by More4ever** [omsrivastava/timezones-list#6]
Some timezones produce `RangeError: Invalid time zone specified`

Could you please sync timezones with actual list

https://www.iana.org/time-zones

Example of invalid timezone:
https://github.com/omsrivastava/timezones-list/blob/c1fa0ebe1ed77def1d29cb923ed7c51c9d213c94/src/timezones.json#L543

**Comment by LottaLauEtteplan** [comment]
I found two invalid time zones here:
"label":"America/AnguillaSandy Hill (GMT-04:00)"
"label":"Pacific/GuamVillage (GMT+10:00)"

**Comment by raphaelpinel** [comment]
Yes, we are getting this error. It seems that there should be a space between "Anguilla" and "Sandy Hill"
Here is the error (React application in Chrome), using timezones-list version 3.02:
`RangeError: Invalid time zone specified: America/AnguillaSandy Hill`

**Comment by raphaelpinel** [comment]
@omsrivastava thanks for merging. But why is there not a new package version on npm? Did the pipeline fail? Could you please check? Thanks a lot.
