### ISSUE TITLE
Wrong name for Kyiv

### ISSUE THREAD

**Issue by NikolaNbgd** [omsrivastava/timezones-list#9]
Hi,
We received a request from a Ukraine customer to change the time zone name from Kiev to Kyiv, which correct name.

![image (1)](https://user-images.githubusercontent.com/18666816/221165943-65ffdf46-fd57-4553-8e3e-f40ad54071ae.png)

**Google search**

![image](https://user-images.githubusercontent.com/18666816/221166127-8523e782-aeea-43f2-aff2-7a9b450fb31e.png)

**Comment by omsrivastava** [comment]
PR is merged with the issue fixed. Will be deployed soon -
https://github.com/omsrivastava/timezones-list/pull/10
